<Project>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

</Project>
