<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CodeAnalysisVersion>4.8.0</CodeAnalysisVersion>
        <MicrosoftAspNetVersion>9.0.3</MicrosoftAspNetVersion>
        <AspireVersion>9.1.0</AspireVersion>
        <OpenTelemetryVersion>1.11.0</OpenTelemetryVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.Data.SqlClient" Version="6.1.2" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="9.0.10" />
        <PackageVersion Include="Microsoft.TypeScript.MSBuild" Version="5.9.2" />
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
        <PackageVersion Include="ImageProcessor.Core" Version="1.1.0" />
        <PackageVersion Include="Svg" Version="3.4.7" />
        <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="9.10.0" />
        <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="9.5.1" />
        <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.13.1" />
        <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.13.1" />
        <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
        <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
        <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.12.0" />
        <PackageVersion Include="Aspire.Hosting.AppHost" Version="9.5.1" />
        <PackageVersion Include="Aspire.Hosting.SqlServer" Version="9.5.1" />
        <PackageVersion Include="coverlet.collector" Version="6.0.0" />
        <PackageVersion Include="FakeItEasy" Version="8.3.0" />
        <PackageVersion Include="FluentAssertions" Version="6.12.1" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
        <PackageVersion Include="Moq" Version="4.20.72" />
        <PackageVersion Include="xunit" Version="2.5.3" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.3" />
        <PackageVersion Include="Magick.NET-Q8-AnyCPU" Version="14.9.0" />
        <PackageVersion Include="Magick.NET.SystemDrawing" Version="8.0.11" />
        <PackageVersion Include="Magick.NET.SystemWindowsMedia" Version="8.0.11" />
    </ItemGroup>
</Project>
